name: Rust

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install dependencies
      run: |
        sudo apt-get install -y libgtk-3-dev libgdk-pixbuf2.0-dev libpango1.0-dev libatk1.0-dev \
          libcairo2-dev libsoup-3.0-dev libjavascriptcoregtk-4.1-dev webkit2gtk-4.1 libxdo-dev

    - name: Build
      run: cargo build --verbose
    
    - name: Run tests
      run: cargo test --verbose